#!/bin/bash

# Install Lume.OLED
sudo -H pip3 install --upgrade luma.oled

# Enable SPI interface
if grep -q -E "^#?dtparam=spi=" /boot/config.txt; then
	sed -i 's/^#\?dtparam=spi=.*/dtparam=spi=on/' /boot/config.txt
else
	echo "dtparam=spi=on" >> /boot/config.txt
fi
