name: Build Debian Package On PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'debian/changelog'

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    strategy:
      fail-fast: false
      matrix:
        distro: [buster,bullseye]
        arch: [armhf,arm64]

    name: ${{ matrix.distro }} ${{ matrix.arch }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sbuild for ${{ matrix.distro }} ${{ matrix.arch }}
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Archive artifacts and upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-fpms-${{ matrix.distro }}-${{ matrix.arch }}
          path: ${{ steps.build-debian-package.outputs.deb-package }}
        
      - name: Notify Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          message: '{"channel":"CFRDLJJDU","text": "${{ github.repository }} <${{ github.event.commits[0].url }}/checks|${{ github.workflow }}> *${{ job.status }}* (${{ matrix.distro }}\${{ matrix.arch }}) --- <${{ github.event.commits[0].url }}|${{ github.event.commits[0].message }}> by ${{ github.event.commits[0].author.name }}"}'
        if: always()
        uses: pullreminders/slack-action@master
        with:
          args: ${{ toJSON(env.message) }}